name: PR Title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  pull-requests: read # required to read PR title and post lint status

jobs:
  conventional-pr-title:
    uses: jamestelfer/.github/.github/workflows/conventional-pr-title.yml@eff8850f2783ed3efaff0d0e9dcb6b6d2fc0935c # main
